[2023-04-11 00:42:30,987] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.44:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:34,952] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:34] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:34,960] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:34] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:35,052] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:35] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:35,077] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:35] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:35,078] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:35] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:35,081] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:35] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:36,867] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:36] "GET /openapi/redoc HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:36,884] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:36] "GET /openapi/static/js/redoc.standalone.js HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:36,996] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:36] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:36,996] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:36] "GET /openapi/redoc HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:42:38,368] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:42:38] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:16,947] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:16] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:18,719] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:18] "GET /openapi/rapidoc HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:18,743] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:18] "GET /openapi/static/js/rapidoc-min.js HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:18,861] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:18] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:18,867] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:18] "GET /openapi/rapidoc HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:19,094] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:19] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:27,827] ERROR log_exception() L1449 Exception on /pessoa [GET] - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "G:\Repositorios\MVP -- PUC\back-end\app.py", line 88, in get_pessoa
    pessoa_id = query.id
AttributeError: 'PessoaBuscaSchema' object has no attribute 'id'
[2023-04-11 00:43:27,831] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:27] "[35m[1mGET /pessoa HTTP/1.1[0m" 500 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:36,931] WARNING add_pessoa() L54   Erro ao adicionar pessoa 'Tiago', Não foi possível salvar nova pessoa :/ - call_trace=G:\Repositorios\MVP -- PUC\back-end\app.py L54  
[2023-04-11 00:43:36,932] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:36] "[31m[1mPOST /pessoa HTTP/1.1[0m" 400 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:45,869] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:45] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:47,351] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:47] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:47,371] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:47] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:47,374] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:47] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:47,374] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:47] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:47,499] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:47] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:47,552] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:47] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:43:56,265] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:43:56] "GET /pessoas HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
