[2023-04-11 00:44:18,612] ERROR log_exception() L1449 Exception on /pessoa [GET] - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "G:\Repositorios\MVP -- PUC\back-end\app.py", line 88, in get_pessoa
    pessoa_id = query.id
AttributeError: 'PessoaBuscaSchema' object has no attribute 'id'
[2023-04-11 00:44:18,617] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:44:18] "[35m[1mGET /pessoa?nome=Tiagos HTTP/1.1[0m" 500 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:44:40,418] ERROR log_exception() L1449 Exception on /pessoa [GET] - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\scaffold.py", line 109, in wrapper
    resp = _do_wrapper(
  File "C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "G:\Repositorios\MVP -- PUC\back-end\app.py", line 88, in get_pessoa
    pessoa_id = query.id
AttributeError: 'PessoaBuscaSchema' object has no attribute 'id'
[2023-04-11 00:44:40,421] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:44:40] "[35m[1mGET /pessoa?nome=Tiago HTTP/1.1[0m" 500 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 00:44:54,275] INFO _log() L224  192.168.0.44 - - [11/Apr/2023 00:44:54] "GET /pessoas HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
